const REQUIRED = 400;
const INVALID = 401;
const DUPLICATE = 409;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const SUCCESS = 200;

export { REQUIRED, INVALID, DUPLICATE, NOT_FOUND, SERVER_ERROR, SUCCESS };
