const REQUIRED = 400;
const DUPLICATE_ERROR = 409;
const NOT_FOUND_ERROR = 404;
const SERVER_ERROR = 500;
const SUCCESS = 200;

export { REQUIRED, DUPLICATE_ERROR, NOT_FOUND_ERROR, SERVER_ERROR, SUCCESS };
